/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesUpiMicroSpendingRouteImport } from './routes/guides.upi-micro-spending'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated.transactions'
import { Route as AuthenticatedTermsRouteImport } from './routes/_authenticated.terms'
import { Route as AuthenticatedSplitSettleRouteImport } from './routes/_authenticated.split-settle'
import { Route as AuthenticatedSmsIntelligenceRouteImport } from './routes/_authenticated.sms-intelligence'
import { Route as AuthenticatedSmartCategorizationRouteImport } from './routes/_authenticated.smart-categorization'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSalarySettingsRouteImport } from './routes/_authenticated.salary-settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated.privacy'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated.planner'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedNotificationSettingsRouteImport } from './routes/_authenticated.notification-settings'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated.menu'
import { Route as AuthenticatedLocalizationRouteImport } from './routes/_authenticated.localization'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated.loans'
import { Route as AuthenticatedInvestmentsRouteImport } from './routes/_authenticated.investments'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated.insights'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated.import'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated.goals'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated.feedback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated.categories'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated.budgets'
import { Route as AuthenticatedAppearanceRouteImport } from './routes/_authenticated.appearance'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated.about'
import { Route as AuthenticatedInsightsIndexRouteImport } from './routes/_authenticated.insights.index'
import { Route as AuthenticatedInsightsWeeklyRouteImport } from './routes/_authenticated.insights.weekly'
import { Route as AuthenticatedInsightsReportRouteImport } from './routes/_authenticated.insights.report'
import { Route as AuthenticatedInsightsCoachRouteImport } from './routes/_authenticated.insights.coach'
import { Route as AuthenticatedInsightsBehaviorRouteImport } from './routes/_authenticated.insights.behavior'
import { Route as AuthenticatedInsightsAlertsRouteImport } from './routes/_authenticated.insights.alerts'
import { Route as AuthenticatedInsightsAiCoachRouteImport } from './routes/_authenticated.insights.ai-coach'
import { Route as AuthenticatedInsightsAiRouteImport } from './routes/_authenticated.insights.ai'
import { Route as AuthenticatedInsightsAiCoachResultsRouteImport } from './routes/_authenticated.insights.ai-coach.results'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesUpiMicroSpendingRoute = GuidesUpiMicroSpendingRouteImport.update({
  id: '/guides/upi-micro-spending',
  path: '/guides/upi-micro-spending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTermsRoute = AuthenticatedTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSplitSettleRoute =
  AuthenticatedSplitSettleRouteImport.update({
    id: '/split-settle',
    path: '/split-settle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSmsIntelligenceRoute =
  AuthenticatedSmsIntelligenceRouteImport.update({
    id: '/sms-intelligence',
    path: '/sms-intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSmartCategorizationRoute =
  AuthenticatedSmartCategorizationRouteImport.update({
    id: '/smart-categorization',
    path: '/smart-categorization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalarySettingsRoute =
  AuthenticatedSalarySettingsRouteImport.update({
    id: '/salary-settings',
    path: '/salary-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationSettingsRoute =
  AuthenticatedNotificationSettingsRouteImport.update({
    id: '/notification-settings',
    path: '/notification-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLocalizationRoute =
  AuthenticatedLocalizationRouteImport.update({
    id: '/localization',
    path: '/localization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvestmentsRoute =
  AuthenticatedInvestmentsRouteImport.update({
    id: '/investments',
    path: '/investments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppearanceRoute = AuthenticatedAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsIndexRoute =
  AuthenticatedInsightsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedInsightsWeeklyRoute =
  AuthenticatedInsightsWeeklyRouteImport.update({
    id: '/weekly',
    path: '/weekly',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedInsightsReportRoute =
  AuthenticatedInsightsReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedInsightsCoachRoute =
  AuthenticatedInsightsCoachRouteImport.update({
    id: '/coach',
    path: '/coach',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedInsightsBehaviorRoute =
  AuthenticatedInsightsBehaviorRouteImport.update({
    id: '/behavior',
    path: '/behavior',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedInsightsAlertsRoute =
  AuthenticatedInsightsAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedInsightsAiCoachRoute =
  AuthenticatedInsightsAiCoachRouteImport.update({
    id: '/ai-coach',
    path: '/ai-coach',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedInsightsAiRoute = AuthenticatedInsightsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedInsightsRoute,
} as any)
const AuthenticatedInsightsAiCoachResultsRoute =
  AuthenticatedInsightsAiCoachResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedInsightsAiCoachRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AuthenticatedAboutRoute
  '/appearance': typeof AuthenticatedAppearanceRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/import': typeof AuthenticatedImportRoute
  '/insights': typeof AuthenticatedInsightsRouteWithChildren
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/localization': typeof AuthenticatedLocalizationRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/salary-settings': typeof AuthenticatedSalarySettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smart-categorization': typeof AuthenticatedSmartCategorizationRoute
  '/sms-intelligence': typeof AuthenticatedSmsIntelligenceRoute
  '/split-settle': typeof AuthenticatedSplitSettleRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/guides/upi-micro-spending': typeof GuidesUpiMicroSpendingRoute
  '/insights/ai': typeof AuthenticatedInsightsAiRoute
  '/insights/ai-coach': typeof AuthenticatedInsightsAiCoachRouteWithChildren
  '/insights/alerts': typeof AuthenticatedInsightsAlertsRoute
  '/insights/behavior': typeof AuthenticatedInsightsBehaviorRoute
  '/insights/coach': typeof AuthenticatedInsightsCoachRoute
  '/insights/report': typeof AuthenticatedInsightsReportRoute
  '/insights/weekly': typeof AuthenticatedInsightsWeeklyRoute
  '/insights/': typeof AuthenticatedInsightsIndexRoute
  '/insights/ai-coach/results': typeof AuthenticatedInsightsAiCoachResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AuthenticatedAboutRoute
  '/appearance': typeof AuthenticatedAppearanceRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/import': typeof AuthenticatedImportRoute
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/localization': typeof AuthenticatedLocalizationRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/salary-settings': typeof AuthenticatedSalarySettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smart-categorization': typeof AuthenticatedSmartCategorizationRoute
  '/sms-intelligence': typeof AuthenticatedSmsIntelligenceRoute
  '/split-settle': typeof AuthenticatedSplitSettleRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/guides/upi-micro-spending': typeof GuidesUpiMicroSpendingRoute
  '/insights/ai': typeof AuthenticatedInsightsAiRoute
  '/insights/ai-coach': typeof AuthenticatedInsightsAiCoachRouteWithChildren
  '/insights/alerts': typeof AuthenticatedInsightsAlertsRoute
  '/insights/behavior': typeof AuthenticatedInsightsBehaviorRoute
  '/insights/coach': typeof AuthenticatedInsightsCoachRoute
  '/insights/report': typeof AuthenticatedInsightsReportRoute
  '/insights/weekly': typeof AuthenticatedInsightsWeeklyRoute
  '/insights': typeof AuthenticatedInsightsIndexRoute
  '/insights/ai-coach/results': typeof AuthenticatedInsightsAiCoachResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/appearance': typeof AuthenticatedAppearanceRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRouteWithChildren
  '/_authenticated/investments': typeof AuthenticatedInvestmentsRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/localization': typeof AuthenticatedLocalizationRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/salary-settings': typeof AuthenticatedSalarySettingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/smart-categorization': typeof AuthenticatedSmartCategorizationRoute
  '/_authenticated/sms-intelligence': typeof AuthenticatedSmsIntelligenceRoute
  '/_authenticated/split-settle': typeof AuthenticatedSplitSettleRoute
  '/_authenticated/terms': typeof AuthenticatedTermsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/guides/upi-micro-spending': typeof GuidesUpiMicroSpendingRoute
  '/_authenticated/insights/ai': typeof AuthenticatedInsightsAiRoute
  '/_authenticated/insights/ai-coach': typeof AuthenticatedInsightsAiCoachRouteWithChildren
  '/_authenticated/insights/alerts': typeof AuthenticatedInsightsAlertsRoute
  '/_authenticated/insights/behavior': typeof AuthenticatedInsightsBehaviorRoute
  '/_authenticated/insights/coach': typeof AuthenticatedInsightsCoachRoute
  '/_authenticated/insights/report': typeof AuthenticatedInsightsReportRoute
  '/_authenticated/insights/weekly': typeof AuthenticatedInsightsWeeklyRoute
  '/_authenticated/insights/': typeof AuthenticatedInsightsIndexRoute
  '/_authenticated/insights/ai-coach/results': typeof AuthenticatedInsightsAiCoachResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/about'
    | '/appearance'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/feedback'
    | '/goals'
    | '/import'
    | '/insights'
    | '/investments'
    | '/loans'
    | '/localization'
    | '/menu'
    | '/notification-settings'
    | '/notifications'
    | '/planner'
    | '/privacy'
    | '/reports'
    | '/salary-settings'
    | '/settings'
    | '/smart-categorization'
    | '/sms-intelligence'
    | '/split-settle'
    | '/terms'
    | '/transactions'
    | '/guides/upi-micro-spending'
    | '/insights/ai'
    | '/insights/ai-coach'
    | '/insights/alerts'
    | '/insights/behavior'
    | '/insights/coach'
    | '/insights/report'
    | '/insights/weekly'
    | '/insights/'
    | '/insights/ai-coach/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/about'
    | '/appearance'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/feedback'
    | '/goals'
    | '/import'
    | '/investments'
    | '/loans'
    | '/localization'
    | '/menu'
    | '/notification-settings'
    | '/notifications'
    | '/planner'
    | '/privacy'
    | '/reports'
    | '/salary-settings'
    | '/settings'
    | '/smart-categorization'
    | '/sms-intelligence'
    | '/split-settle'
    | '/terms'
    | '/transactions'
    | '/guides/upi-micro-spending'
    | '/insights/ai'
    | '/insights/ai-coach'
    | '/insights/alerts'
    | '/insights/behavior'
    | '/insights/coach'
    | '/insights/report'
    | '/insights/weekly'
    | '/insights'
    | '/insights/ai-coach/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/about'
    | '/_authenticated/appearance'
    | '/_authenticated/budgets'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedback'
    | '/_authenticated/goals'
    | '/_authenticated/import'
    | '/_authenticated/insights'
    | '/_authenticated/investments'
    | '/_authenticated/loans'
    | '/_authenticated/localization'
    | '/_authenticated/menu'
    | '/_authenticated/notification-settings'
    | '/_authenticated/notifications'
    | '/_authenticated/planner'
    | '/_authenticated/privacy'
    | '/_authenticated/reports'
    | '/_authenticated/salary-settings'
    | '/_authenticated/settings'
    | '/_authenticated/smart-categorization'
    | '/_authenticated/sms-intelligence'
    | '/_authenticated/split-settle'
    | '/_authenticated/terms'
    | '/_authenticated/transactions'
    | '/guides/upi-micro-spending'
    | '/_authenticated/insights/ai'
    | '/_authenticated/insights/ai-coach'
    | '/_authenticated/insights/alerts'
    | '/_authenticated/insights/behavior'
    | '/_authenticated/insights/coach'
    | '/_authenticated/insights/report'
    | '/_authenticated/insights/weekly'
    | '/_authenticated/insights/'
    | '/_authenticated/insights/ai-coach/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesUpiMicroSpendingRoute: typeof GuidesUpiMicroSpendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/upi-micro-spending': {
      id: '/guides/upi-micro-spending'
      path: '/guides/upi-micro-spending'
      fullPath: '/guides/upi-micro-spending'
      preLoaderRoute: typeof GuidesUpiMicroSpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terms': {
      id: '/_authenticated/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedTermsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/split-settle': {
      id: '/_authenticated/split-settle'
      path: '/split-settle'
      fullPath: '/split-settle'
      preLoaderRoute: typeof AuthenticatedSplitSettleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sms-intelligence': {
      id: '/_authenticated/sms-intelligence'
      path: '/sms-intelligence'
      fullPath: '/sms-intelligence'
      preLoaderRoute: typeof AuthenticatedSmsIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/smart-categorization': {
      id: '/_authenticated/smart-categorization'
      path: '/smart-categorization'
      fullPath: '/smart-categorization'
      preLoaderRoute: typeof AuthenticatedSmartCategorizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salary-settings': {
      id: '/_authenticated/salary-settings'
      path: '/salary-settings'
      fullPath: '/salary-settings'
      preLoaderRoute: typeof AuthenticatedSalarySettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notification-settings': {
      id: '/_authenticated/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof AuthenticatedNotificationSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/localization': {
      id: '/_authenticated/localization'
      path: '/localization'
      fullPath: '/localization'
      preLoaderRoute: typeof AuthenticatedLocalizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investments': {
      id: '/_authenticated/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthenticatedInvestmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appearance': {
      id: '/_authenticated/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AuthenticatedAppearanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/': {
      id: '/_authenticated/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof AuthenticatedInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/weekly': {
      id: '/_authenticated/insights/weekly'
      path: '/weekly'
      fullPath: '/insights/weekly'
      preLoaderRoute: typeof AuthenticatedInsightsWeeklyRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/report': {
      id: '/_authenticated/insights/report'
      path: '/report'
      fullPath: '/insights/report'
      preLoaderRoute: typeof AuthenticatedInsightsReportRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/coach': {
      id: '/_authenticated/insights/coach'
      path: '/coach'
      fullPath: '/insights/coach'
      preLoaderRoute: typeof AuthenticatedInsightsCoachRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/behavior': {
      id: '/_authenticated/insights/behavior'
      path: '/behavior'
      fullPath: '/insights/behavior'
      preLoaderRoute: typeof AuthenticatedInsightsBehaviorRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/alerts': {
      id: '/_authenticated/insights/alerts'
      path: '/alerts'
      fullPath: '/insights/alerts'
      preLoaderRoute: typeof AuthenticatedInsightsAlertsRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/ai-coach': {
      id: '/_authenticated/insights/ai-coach'
      path: '/ai-coach'
      fullPath: '/insights/ai-coach'
      preLoaderRoute: typeof AuthenticatedInsightsAiCoachRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/ai': {
      id: '/_authenticated/insights/ai'
      path: '/ai'
      fullPath: '/insights/ai'
      preLoaderRoute: typeof AuthenticatedInsightsAiRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/insights/ai-coach/results': {
      id: '/_authenticated/insights/ai-coach/results'
      path: '/results'
      fullPath: '/insights/ai-coach/results'
      preLoaderRoute: typeof AuthenticatedInsightsAiCoachResultsRouteImport
      parentRoute: typeof AuthenticatedInsightsAiCoachRoute
    }
  }
}

interface AuthenticatedInsightsAiCoachRouteChildren {
  AuthenticatedInsightsAiCoachResultsRoute: typeof AuthenticatedInsightsAiCoachResultsRoute
}

const AuthenticatedInsightsAiCoachRouteChildren: AuthenticatedInsightsAiCoachRouteChildren =
  {
    AuthenticatedInsightsAiCoachResultsRoute:
      AuthenticatedInsightsAiCoachResultsRoute,
  }

const AuthenticatedInsightsAiCoachRouteWithChildren =
  AuthenticatedInsightsAiCoachRoute._addFileChildren(
    AuthenticatedInsightsAiCoachRouteChildren,
  )

interface AuthenticatedInsightsRouteChildren {
  AuthenticatedInsightsAiRoute: typeof AuthenticatedInsightsAiRoute
  AuthenticatedInsightsAiCoachRoute: typeof AuthenticatedInsightsAiCoachRouteWithChildren
  AuthenticatedInsightsAlertsRoute: typeof AuthenticatedInsightsAlertsRoute
  AuthenticatedInsightsBehaviorRoute: typeof AuthenticatedInsightsBehaviorRoute
  AuthenticatedInsightsCoachRoute: typeof AuthenticatedInsightsCoachRoute
  AuthenticatedInsightsReportRoute: typeof AuthenticatedInsightsReportRoute
  AuthenticatedInsightsWeeklyRoute: typeof AuthenticatedInsightsWeeklyRoute
  AuthenticatedInsightsIndexRoute: typeof AuthenticatedInsightsIndexRoute
}

const AuthenticatedInsightsRouteChildren: AuthenticatedInsightsRouteChildren = {
  AuthenticatedInsightsAiRoute: AuthenticatedInsightsAiRoute,
  AuthenticatedInsightsAiCoachRoute:
    AuthenticatedInsightsAiCoachRouteWithChildren,
  AuthenticatedInsightsAlertsRoute: AuthenticatedInsightsAlertsRoute,
  AuthenticatedInsightsBehaviorRoute: AuthenticatedInsightsBehaviorRoute,
  AuthenticatedInsightsCoachRoute: AuthenticatedInsightsCoachRoute,
  AuthenticatedInsightsReportRoute: AuthenticatedInsightsReportRoute,
  AuthenticatedInsightsWeeklyRoute: AuthenticatedInsightsWeeklyRoute,
  AuthenticatedInsightsIndexRoute: AuthenticatedInsightsIndexRoute,
}

const AuthenticatedInsightsRouteWithChildren =
  AuthenticatedInsightsRoute._addFileChildren(
    AuthenticatedInsightsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAppearanceRoute: typeof AuthenticatedAppearanceRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRouteWithChildren
  AuthenticatedInvestmentsRoute: typeof AuthenticatedInvestmentsRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedLocalizationRoute: typeof AuthenticatedLocalizationRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedNotificationSettingsRoute: typeof AuthenticatedNotificationSettingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalarySettingsRoute: typeof AuthenticatedSalarySettingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSmartCategorizationRoute: typeof AuthenticatedSmartCategorizationRoute
  AuthenticatedSmsIntelligenceRoute: typeof AuthenticatedSmsIntelligenceRoute
  AuthenticatedSplitSettleRoute: typeof AuthenticatedSplitSettleRoute
  AuthenticatedTermsRoute: typeof AuthenticatedTermsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAppearanceRoute: AuthenticatedAppearanceRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRouteWithChildren,
  AuthenticatedInvestmentsRoute: AuthenticatedInvestmentsRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedLocalizationRoute: AuthenticatedLocalizationRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedNotificationSettingsRoute:
    AuthenticatedNotificationSettingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalarySettingsRoute: AuthenticatedSalarySettingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSmartCategorizationRoute: AuthenticatedSmartCategorizationRoute,
  AuthenticatedSmsIntelligenceRoute: AuthenticatedSmsIntelligenceRoute,
  AuthenticatedSplitSettleRoute: AuthenticatedSplitSettleRoute,
  AuthenticatedTermsRoute: AuthenticatedTermsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesUpiMicroSpendingRoute: GuidesUpiMicroSpendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
